import { Geist, Geist_Mono } from "next/font/google";
import Nav from "../components/global/navBar.js";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 flex items-center justify-center h-[100dvh] overflow-hidden`}>
        
        <div className="w-full h-full sm:w-[430px] sm:h-[932px] bg-brand-grey1 sm:border-[12px] border-purple-400 sm:rounded-[60px] overflow-hidden shadow-2xl flex flex-col relative">
          
          <main className="flex-1 overflow-y-auto scroll-smooth p-4 pt-8 pb-24">
             {children}
          </main>

          <Nav />

        </div>
      </body>
    </html>
  );
}